blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/ultrasardine/email-signature-generator/discussions
    about: Ask questions or start discussions about the project
